config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    resources :orderitems
  end

  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'orders/edit'

  get '/orders/' => 'order#show'

  devise_for :users do resources :orders end

  get '/checkout' => 'cart#createorder'
  get '/users/:id' => 'users#show'
  get '/paymentconfirmation/:id' => 'cart#paymentConfirmation'

  root 'home#index'
  get 'home/index'
  get '/home' => 'home#index'

  get 'cart/index'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/clearcart' => 'cart#clear'
  get 'increase/:id', to: 'cart#increase'
  get 'reduce/:id', to: 'cart#reduce'
  get 'remove/:id', to: 'cart#remove'

  get '/login' => 'user#login'
  get '/logout' => 'user#logout'

  resources :productitems
    resources :new
    resources :create
    resources :show
    resources :edit
    resources :delete

  get 'productitems/new'
  get 'productitems/show'
  get 'productitems/edit'
  get 'productitems/delete'
  get '/productitems' => 'productitems#index'
  get '/productitems' => 'productitems#new'
  get '/productitems' => 'productitems#show'
  get '/productitems' => 'productitems#edit'
  get '/productitems' => 'productitems#delete'

end

app/models/productitem.rb
class Productitem < ApplicationRecord
  mount_uploader :productimage, ProductImageUploader

  # # User Avatar Validation
  validates_integrity_of  :productimage
  validates_processing_of :productimage

  def productitem_params
    params.require(:productitem).permit(:productname, :description, :price, :brand, :productimage)
  end

end

app/controllers/productitems_controller.rb
class ProductitemsController < ApplicationController
  before_action :set_productitem, only: [:show, :edit, :update, :destroy]

  # GET /productitems
  # GET /productitems.json
  def index
    @productitem = Productitem.all
  end

  # GET /productitems/1
  # GET /productitems/1.json
  def show
    @productitem = Productitem.find(params[:id])
  end

  # GET /productitems/new
  def new
    @productitem = Productitem.new
  end

  # GET /productitems/1/edit
  def edit
    @productitem = Productitem.find(params[:id])
  end

  # POST /productitems
  # POST /productitems.json
  def create
  #render plain: params[:productitem].inspect
    @productitem = Productitem.new(productitem_params)

    respond_to do |format|
      if @productitem.save
        format.html { redirect_to @productitem, notice: 'Product item was successfully created.' }
        format.json { render :show, status: :created, location: @productitem }
      else
        format.html { render :new }
        format.json { render json: @productitem.errors, status: :unprocessable_entity }
      end
    end


    def productitem_params
      params.require(:productitem).permit(:productname, :description, :price, :brand, :productimage, :productimage_cache)
    end
  end

  # PATCH/PUT /productitems/1
  # PATCH/PUT /productitems/1.json
  def update
    respond_to do |format|
      if @productitem.update(productitem_params)
        format.html { redirect_to @productitem, notice: 'Productitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @productitem }
      else
        format.html { render :edit }
        format.json { render json: @productitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productitems/1
  # DELETE /productitems/1.json
  def destroy
    @productitem.destroy
    respond_to do |format|
      format.html { redirect_to productitems_url, notice: 'Productitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    def set_productitem
      @productitem = Productitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def productitem_params
      params.require(:productitem).permit(:productname, :description, :price, :brand, :productimage, :productimage_cache)
  end
end

app/helpers/productitems_helper.rb
module ProductitemsHelper
end

app/views/productitems/_form.html.erb
<div class="mainCont">
<%= form_with(model: productitem, local: true) do |form| %>
  <% if productitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productitem.errors.count, "error") %> prohibited this productitem from being saved:</h2>

      <ul>
        <% productitem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :productname %>
    <%= form.text_field :productname, id: :productitem_name, :type =>"text"%>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :productitem_description, :type =>"text" %>
  </div>
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field  :price, id: :productitem_price, :type =>"text" %>
  </div>
  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :productitem_brand, :type =>"text" %>
  </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/productitems/edit.html.erb
<h1>Editing Productitem</h1>

<%= render 'form', productitem: @productitem %>

<%= link_to 'Show', @productitem %> |
<%= link_to 'Back', productitems_path %>

app/views/productitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ProductItems</h1>

<table>
  <thead>
  <tr>
    <th>Productname</th>
    <th>Description</th>
    <th>Price</th>
    <th>Brand</th>
    <th colspan="3"></th>
  </tr>
  </thead>
</table>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productitem.each do |productitem| %>
      <tr>
        <% if productitem.productimage_url %>
        <td><%= image_tag productitem.productimage_url(:thumb) %></td>
        <td><%= productitem.productname %></td>
        <td><%= productitem.description %></td>
        <td><%= productitem.price %></td>
        <td><%= productitem.brand %></td>
        <% end %>
        <% if user_signed_in? %>
        <td><%= link_to 'Show', productitem %></td>
        <% end %>
        <% if user_admin %>
        <td><%= link_to 'Edit', edit_productitem_path(productitem)%></td>
        <td><%= link_to 'Destroy', productitem, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
        <% if user_signed_in? %>
        <td><a href="/cart/<%= productitem.id %>" class="button">Add To Cart</a></td>
        <% end %>
      </tr>
      <% end %>
      <ul>
      <% if user_admin %>
      <li><%= link_to 'New Product Item', new_productitem_path %></li>
      <% end %>
      </ul>
  </tbody>
</table>
<br>
<%= link_to "Home", "home#index" %>

app/views/productitems/new.html.erb
<%= form_with scope: :productitem, url: productitems_path, local: true do |form| %>

  <% if @productitem.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@productitem.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @productitem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productname %>
    <%= form.text_field :productname %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <p>
      <label>Product Image</label>
      <%= image_tag(@productitem.productimage_url) if @productitem.productimage? %>
      <%= form.file_field :productimage %>
      <%= form.hidden_field :productimage_cache %>
    </p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
<%= link_to 'Back', productitems_path %>

app/views/productitems/show.html.erb
<p id="notice"><%= notice %></p>

<% if @productitem.productimage_url %>
  <%= image_tag @productitem.productimage_url(:medium) %>
<% end %>

<p>
  <strong>Product Name:</strong>
  <%= @productitem.productname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @productitem.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @productitem.price %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @productitem.brand %>
</p>
<% if user_signed_in? %>
<td><a href="/cart/<%= @productitem.id %>" class="button">Add To Cart</a></td>
<% end %>
<% if user_admin %>
<%= link_to 'Edit', edit_productitem_path(@productitem) %> |
<% end %>
<%= link_to 'Back', productitems_path %>